### PR TITLE
Projects

### PR DESCRIPTION
**Pull request by riskydissonance**
- All PoshC2 projects are stored in /var/poshc2 (this is in line with where program data should be stored for system-wide programs on *nix systems)
- There’s a new command `posh-project` which is used to create or switch projects, making it much easier to have multiple on the go at the same time
    - E.g. posh-project –n project-x will create a new project directory /var/poshc2/project-x and do setup
          - `posh-project –s project-x` will switch to **project-x** (restarts of the server & implant handler required)
    - The **config.yml** file for each project is stored in the project directory alongside everything else, so you no longer have to back it up to update posh or if switch projects
- A clone of PoshC2 is no longer required if using Docker as we build and publish images to Docker Hub, so you can just curl and run `Install-for-Docker.sh` (instead of Install.sh), which basically just curls down a few scripts and nothing else, then run posh in the usual way without having to build anything or worry about dependencies etc.
- If using the traditional clone-and-install method then the install directory is now programmatically determined when running, so you can clone it to ~/PoshC2, /tmp/PoshC2, /opt/MyPoshC2Install etc wherever and not have to worry about it being set as an environment variable or in the config.
- This means that both the **PoshInstallDirectory** and **PoshProjectDirectory** are no longer needed and have been removed from the config file.
- You can specify Git branches or Docker tags to use when running the Install/Docker scripts in addition to `posh-update`.
    - E.g. `./Install.sh -b dev` will install the dev branch. Curl commands in README updated.
    - `posh-update -b dev` will update to latest dev branch
    -  `posh -t latest -u <username>` (when using Docker) will use the `latest` image when running PoshC2.
- You can specify the PoshC2 clone directory with the `-p` option to `Install.sh`
- Scripts have been cleaned up and homogenised so that they have consistent behaviour and parameters, with common code being pulled out to avoid duplication.
- README cleaned up and updated
- Added Docker CI Widget to reflect new Docker CI status which automatically builds images on master/dev/version tags.
- Various code refactorings and clean up.
- Install script now updates the PoshC2 repo if it's being run locally and for an existing repository
    - Existing changes are stashed so they're not lost.
- Refactor database code so all common code is pulled out and only specifics are in the DBSqlite/DBPostgres files
    - Rest of the codebase then just uses the generic 'DB' without having to know the difference
- Add Dynamic Payload creation by importing any module dropped into `poshc2/server/payloads/` and executing the `create_payloads(payloads, name)` function (macro generation pulled out into Macro-Payloads.py as an example).

### CODE REVIEW

**Comment by riskydissonance** [comment]
poshc2.readthedocs.io will need updating, on the list for when this is reviewed/complete and merged.

**Comment by benpturner** [comment]
When I ran the install, there was an error on line 37. Also my /usr/bin/ now looks like this and I cannot run the posh-project command

image

**Comment by benpturner** [comment]
This is how I ran the install - ./Install.sh -b projects

**Comment by benpturner** [comment]
That fix now works the install, although when no -p option is specified it puts the location as "."

**Comment by benpturner** [comment]
Can you add a posh-project -l option to list all the projects

**Comment by benpturner** [comment]
Also show where the projects are located - $POSH_PROJECTS_DIR

**Comment by riskydissonance** [comment]
image

Added `posh-project -l`

**Comment by riskydissonance** [comment]
image
Install script should be good to go.

**Comment by benpturner** [comment]
Still get this when installing: Doesnt seem to make posh-project executable
image

**Comment by riskydissonance** [comment]
image
Hmm it's fine for me on my Kali VM and I can't see how it wouldn't work...

You are still running `./Install.sh -b projects` at present aye as the `posh-project` script isn't on master?

**Comment by benpturner** [comment]
Yeah sorted, forgot about the branch element. Still having some issues
image

**Comment by riskydissonance** [comment]
Bloomin' different versions of linux storing `ls` in different places, fixed.

**Comment by benpturner** [comment]
image

**Comment by riskydissonance** [comment]
@benpturner once more with feeling

**Comment by benpturner** [comment]
image

**Comment by benpturner** [comment]
Some issues with Postgres DB support

**Comment by benpturner** [comment]
Screenshot 2020-07-28 at 21 21 15

**Review by benpturner — APPROVED** [review]

**Pull request merged**
