### PR TITLE
New Power Status Monitoring - PwrStatusTracker.dll

### PR DESCRIPTION
**Pull request by benpturner**
loadpowerstatus

image

### CODE REVIEW

**Review by b4ggio-su — APPROVED** [review]
Looks good. Great to see go live also

**Comment by riskydissonance** [comment]
Changed the merge target to `hosted-files` as the PR contains all the changes from that PR too, so now will only show the powerstatus changes.

**Will need to change it back to dev once the other one is merged however**

**Comment by riskydissonance** [comment]
Looks good, changing the target branch back.

**Comment by riskydissonance** [comment]
Removed the `host-files` commits so this can be merged ahead of that PR if desired.

**Review by riskydissonance — APPROVED** [review]

**Pull request merged**
