### PR TITLE
Added CSharpWinRM from https://github.com/mez-0/CSharpWinRM

### PR DESCRIPTION
**Pull request by Flangvik**

### CODE REVIEW

**Comment by riskydissonance** [comment]
Ah awesome thanks @Flangvik !

Our policy is to only add trusted code so we'll add this change but compile the module ourselves, is there anything extra we need to know for that?

**Comment by Flangvik** [comment]
Nope, just follow the instructions with the original repo (ILMerge part). Awesome

**Comment by BaffledJimmy** [comment]
Beat me to it :D

**Comment by riskydissonance** [comment]
Actually @BaffledJimmy we can't add compiled code from 3rd parties so do you want to add it yourself?

**Comment by BaffledJimmy** [comment]
Not really no, its @Flangvik 's PR :D

**Comment by riskydissonance** [comment]
@BaffledJimmy create a new one 🙄

**Comment by benpturner** [comment]
Closing this down as I've added a feature request. We'll get this added soon

**Pull request closed without merging**
