### PR TITLE
Updated to load SharpHound.ps1 instead as Bloodhound doesn't exist

### PR DESCRIPTION
**Pull request by ZephrFish**

### CODE REVIEW

**Comment by riskydissonance** [comment]
Thanks man

**Comment by ZephrFish** [comment]
No probs, does the Dev branch get merged into master eventually?

**Comment by riskydissonance** [comment]
Aye, but it's volatile and gets reverted/squashed/rebased/amended etc during dev & testing so use it with caution.

**Comment by ZephrFish** [comment]
Fair enough, I'll chuck it on a VM for playing around with

**Pull request merged**
