### PR TITLE
Customisable and randomised url generation scheme for PoshC2

### PR DESCRIPTION
**Pull request by Console**
I've written a small update so URLs can be randomly generated at the start of the Project, it also generates the appropriate rewrite rules for you and places them inside of your projects working directory.

It can either work from a FIXED list of urls (say if purple teaming and you deliberately want signaturable output) or from a wordlist.

When operating from a wordlist it will generate a random number (between 
20 and 75 as coded right now) of random length (between 1 to 10 URI parts, plus a query string extension if a "coinflip" returns a 1).

I've kept the oldurls.txt as a demonstrator file so that it won't deliberately break if anyone deploys to live and doesn't change their proxies, etc.

Also a small dictionary has been provided, at the moment it's just "first names", I've credited the creator in the source code but it's released under an MIT licence so free to use, copy and distribute but ultimately you can switch out the wordlist to whatever you like.

Rewrite rules are generated on the fly and dropped into the project directory under rewrite-rules.txt, it also pre-populates the posh and sharpsocks ip providing they are given in config.py.

More than happy to write a section for RTD in order to document the ways in which you can use the generation method.

A basic test harness to verify the code with different wordlists at least during testing prior to accepting the PR can be placed in the bottom of URLConfig.py:

`test = UrlConfig()`
`print vars(test)`
`print test.fetchQCUrl()`
`print test.generateRandomURL()`
`print test.fetchSocksRewriteRules()`

Then just running URLConfig.py directly will give you testable output. Obviously any method inside the class can be tested in this way, not just those listed above.

Usage:
By default it'll work just fine. Just generate a new project with the latest branch.

However for the different modes:

- To select a different FIXED url list:
-- Make: `urlConfig = UrlConfig("./oldurls.txt")`
-- at the top of Config.py into: `urlConfig = UrlConfig()`
- To specify a different dictionary for random url generation:
-- `urlConfig = UrlConfig(wordList="./newwordlist.txt")`
- To specify a different file for fixed URL selection: `urlConfig = UrlConfig("./urls.txt")`

**Known issue:**
There is a known issue with using a FIXED list of URLs in that if a URL in the list ends with a /, that URL will get dropped. It's just an artefact of the way I'm parsing them at the moment but as it is it doesn't harm anything it just means for example oldurls.txt shows 33 URLs, but in reality only 26 of them will ever be used.

Really I see that use case as a niche application anyway with teams preferring not to specify the oldurls.txt file and just relying on dictionary generation so I'm not particularly fussed to fix it and deleting the trailing / from your list of URLs is pretty quick for a fix.

Oh yeah, and i've fixed the single quote issue I was having before. I simply remove them from any URLs generated on the fly, bit brutal but again doesn't really impact things too much.

### CODE REVIEW

**Comment by Console** [comment]
Having to close. Not ready for use due to interactions with Implant Handler. Needs more bugfixes.

**Comment by Console** [comment]
Argh, chalk it up to it being 02:33am. I was running ImplantHandler as a non-root user. Commit is just fine and everything works.

**Comment by benpturner** [comment]
Hi Rich, 
This looks great but can you remove the two lines from the Config.py. I'd prefer to remove these from here and when you spit out the rewrite-rules.txt it has to be edited there instead if thats ok. This is just easier for those who dont use a C2 proxy and its less confusing in the Config file. 

 poshIP = "127.0.0.1" # Needed for URL Rewrite Rules.
 sharpIP = "127.0.0.1" # Needed for URL Rewrite Rules.

Once those changes are pushed i'll merge this through. 

Cheers

**Comment by benpturner** [comment]
One other thing, its not fully working on Python v3 but i'm working towards this so can you modify your print statements to be print ( "test" )

Thanks

**Pull request merged**
